"""DECLARE CONSTANTS HERE"""

UNIT_COUNTRY_MAPPING = {
    "United States": {
        "price": "USD",
        "distance": "miles",
        "weight": "pounds",
        "length": "inches",
        "volume": "gallons",
        "temperature": "Fahrenheit",
        "area": "square feet",
        "speed": "miles per hour",
        "footwear": "US size",
    },
    "United Kingdom": {
        "price": "GBP",
        "distance": "miles",
        "weight": "stones",
        "length": "inches",
        "volume": "gallons",
        "temperature": "Celsius",
        "area": "square feet",
        "speed": "miles per hour",
        "footwear": "UK size",
    },
    "Canada": {
        "price": "CAD",
        "distance": "kilometers",
        "weight": "kilograms",
        "length": "centimeters",
        "volume": "liters",
        "temperature": "Celsius",
        "area": "square meters",
        "speed": "kilometers per hour",
        "footwear": "US size",
    },
    "Australia": {
        "price": "AUD",
        "distance": "kilometers",
        "weight": "kilograms",
        "length": "centimeters",
        "volume": "liters",
        "temperature": "Celsius",
        "area": "square meters",
        "speed": "kilometers per hour",
        "footwear": "AU size",
    },
    "India": {
        "price": "INR",
        "distance": "kilometers",
        "weight": "kilograms",
        "length": "centimeters",
        "volume": "liters",
        "temperature": "Celsius",
        "area": "square meters",
        "speed": "kilometers per hour",
        "footwear": "UK size",
    },
    "China": {
        "price": "CNY",
        "distance": "kilometers",
        "weight": "kilograms",
        "length": "centimeters",
        "volume": "liters",
        "temperature": "Celsius",
        "area": "square meters",
        "speed": "kilometers per hour",
        "footwear": "EU size",
    },
    "Japan": {
        "price": "JPY",
        "distance": "kilometers",
        "weight": "kilograms",
        "length": "centimeters",
        "volume": "liters",
        "temperature": "Celsius",
        "area": "square meters",
        "speed": "kilometers per hour",
        "footwear": "JP size",
    },
    "South Korea": {
        "price": "KRW",
        "distance": "kilometers",
        "weight": "kilograms",
        "length": "centimeters",
        "volume": "liters",
        "temperature": "Celsius",
        "area": "square meters",
        "speed": "kilometers per hour",
        "footwear": "KR size",
    },
    "Russia": {
        "price": "RUB",
        "distance": "kilometers",
        "weight": "kilograms",
        "length": "centimeters",
        "volume": "liters",
        "temperature": "Celsius",
        "area": "square meters",
        "speed": "kilometers per hour",
        "footwear": "EU size",
    },
    "Brazil": {
        "price": "BRL",
        "distance": "kilometers",
        "weight": "kilograms",
        "length": "centimeters",
        "volume": "liters",
        "temperature": "Celsius",
        "area": "square meters",
        "speed": "kilometers per hour",
        "footwear": "EU size",
    },
}
